package com.isaacphiri22081310810.icutimetableapp

import android.os.Bundle
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import android.widget.*
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import retrofit2.Call
import retrofit2.Callback
import retrofit2.Response

class CoursesActivity : AppCompatActivity() {

    private lateinit var apiService: ApiService
    private lateinit var courseAdapter: CourseAdapter
    private lateinit var programIdSpinner: Spinner // Spinner for program ID

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_courses)

        apiService = RetrofitInstance.create(ApiService::class.java)
        courseAdapter = CourseAdapter(listOf())

        val recyclerView = findViewById<RecyclerView>(R.id.recyclerViewCourses)
        recyclerView.layoutManager = LinearLayoutManager(this)
        recyclerView.adapter = courseAdapter

        programIdSpinner = findViewById(R.id.spinner_program_id)

        fetchPrograms()
        fetchCourses()

        val coursename = findViewById<EditText>(R.id.input_course_name)
        val createCourseButton = findViewById<Button>(R.id.btn_add_course)

        createCourseButton.setOnClickListener {
            val selectedProgramId = programIdSpinner.selectedItem?.toString()?.toIntOrNull()

            if (selectedProgramId == null) {
                Toast.makeText(this, "Please select a valid Program ID", Toast.LENGTH_SHORT).show()
                return@setOnClickListener
            }

            val course = Course(
                courseName = coursename.text.toString(),
                programId = selectedProgramId,
                courseId = null, // Auto-generated by the database
                programName = ""
            )

            apiService.addCourse(course).enqueue(object : Callback<Void> {
                override fun onResponse(call: Call<Void>, response: Response<Void>) {
                    if (response.isSuccessful) {
                        Toast.makeText(this@CoursesActivity, "Course created successfully!", Toast.LENGTH_SHORT).show()
                        fetchCourses()
                    } else {
                        Toast.makeText(this@CoursesActivity, "Failed to create course", Toast.LENGTH_SHORT).show()
                    }
                }

                override fun onFailure(call: Call<Void>, t: Throwable) {
                    Toast.makeText(this@CoursesActivity, "Error: ${t.message}", Toast.LENGTH_SHORT).show()
                }
            })
        }
    }

    private fun fetchPrograms() {
        apiService.getPrograms().enqueue(object : Callback<List<Program>> {
            override fun onResponse(call: Call<List<Program>>, response: Response<List<Program>>) {
                if (response.isSuccessful) {
                    val programs = response.body() ?: listOf()
                    val programIds = programs.map { it.programId }
                    val adapter = ArrayAdapter(this@CoursesActivity, android.R.layout.simple_spinner_item, programIds)
                    adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
                    programIdSpinner.adapter = adapter
                } else {
                    Toast.makeText(this@CoursesActivity, "Failed to fetch programs", Toast.LENGTH_SHORT).show()
                }
            }

            override fun onFailure(call: Call<List<Program>>, t: Throwable) {
                Toast.makeText(this@CoursesActivity, "Error: ${t.message}", Toast.LENGTH_SHORT).show()
            }
        })
    }

    private fun fetchCourses() {
        apiService.getCourses().enqueue(object : Callback<List<Course>> {
            override fun onResponse(call: Call<List<Course>>, response: Response<List<Course>>) {
                if (response.isSuccessful) {
                    courseAdapter.updateData(response.body() ?: listOf())
                } else {
                    Toast.makeText(this@CoursesActivity, "Failed to fetch courses", Toast.LENGTH_SHORT).show()
                }
            }

            override fun onFailure(call: Call<List<Course>>, t: Throwable) {
                Toast.makeText(this@CoursesActivity, "Error: ${t.message}", Toast.LENGTH_SHORT).show()
            }
        })
    }
}
